### PR TITLE
Update to Makie v0.18

### PR DESCRIPTION
**Pull request by jaakkor2**
Tests pass locally. I had to change https://github.com/MakieOrg/OSMMakie.jl/blob/v0.0.5/test/runtests.jl#L48 to `Makie.PlotMethodError`.  Let's see what CI says.  Otherwise I would have kept compatibility with Makie = "0.16, 0.17" and Graphs "0.3".

Note that compat `julia = "1.6"` includes 1.7 and 1.8, so no need to explicitly state those.

### CODE REVIEW

**Comment by fbanning** [comment]
Ah, using `Makie.PlotMethodError` solves the problem of different errors thrown on CI and locally. Nice way to do it and simplify the test suite.

I explicitly had `1.6, 1.7` as the julia versions in the `Project.toml` because that was a bit of additional info which versions we're testing the package with. But I have no objections to only putting `1.6` there.

I suppose you've created a map locally with the updated Makie version and the recipe worked just fine? If so, I don't see any problems with merging this. Thanks for bringing it up. :)

**Review by fbanning — APPROVED** [review]

**Comment by jaakkor2** [comment]
Argh, now I see that `DataInspector(fig)` gives
```
Error in callback:
KeyError: key :_display_text not found
```

**Comment by fbanning** [comment]
Ah yep, that should be related to the changes in the `DataInspector` recipe and its attributes/keywords. See https://github.com/MakieOrg/Makie.jl/pull/2095 for more info on that. I didn't find the time to look into it but it also impacts our ability to bump the `Makie` version on `InteractiveDynamics.jl`. If you already know how the `DataInspector` works, feel free to change the relevant attributes in our use cases here for `OSMMakie`. Otherwise I'll have a look at it once I find the time. :)

**Comment by jaakkor2** [comment]
DataInspector works now, but these three fields I did not quickly find corresponding new ones https://github.com/MakieOrg/OSMMakie.jl/blob/v0.0.5/src/inspection.jl#L18-L20 : `__bbox2D`, `_px_bbox_visible`, `_bbox_visible`.

**Comment by fbanning** [comment]
`__bbox2D` seems to have been removed. The other two were merged into one attribute called `indicator_visible`. Have a look at the tables in [this comment](https://github.com/MakieOrg/Makie.jl/pull/2095#issuecomment-1173086544). It could very well be that we're just using the defaults for this field.

**Comment by fbanning** [comment]
Thank you @jaakkor2 for your help! :)

**Pull request merged**
